macro(check_hidapi_package)
  find_path(HIDAPI_DIR hidapi/hidapi.h ${CMAKE_SOURCE_DIR}/deps/hidapi ${CMAKE_SOURCE_DIR}/deps/hidapi-0.7.0 ${UHID_HIDAPI_DIR})
  if (HIDAPI_DIR-NOTFOUND)
    message(ERROR "Please download and unpack to hidapi to ${CMAKE_SOURCE_DIR}/deps/hidapi")
    message(ERROR ".. or pass a valid -DUHID_HIDAPI_DIR= to cmake")
  else()
    message(STATUS "Using hidapi in ${HIDAPI_DIR}")
  endif()

  set(HIDAPI_INCLUDE_DIRS "${HIDAPI_DIR};${HIDAPI_DIR}/hidapi")
endmacro()

if (WIN32 OR MSYS OR MINGW)
  check_hidapi_package()
  set(HIDAPI_SOURCES "${HIDAPI_DIR}/windows/hid.c")
  set(HIDAPI_LIBRARIES "setupapi")
elseif(APPLE)
  check_hidapi_package()
  set(HIDAPI_SOURCES "${HIDAPI_DIR}/mac/hid.c")
  set(HIDAPI_LIBRARIES "-framework IOKit -framework CoreFoundation")
else()
  FIND_PACKAGE(PkgConfig)
  PKG_CHECK_MODULES(HIDAPI hidapi-libusb)
  add_cflag_if_supported( "-fPIC ")
endif()
