macro(check_hidapi_package)
  find_path(HIDAPI_DIR hidapi/hidapi.h ${CMAKE_SOURCE_DIR}/deps/hidapi ${CMAKE_SOURCE_DIR}/deps/hidapi-0.7.0 ${UHID_HIDAPI_DIR})
  if (HIDAPI_DIR-NOTFOUND)
    message(ERROR "Please download and unpack to hidapi to ${CMAKE_SOURCE_DIR}/deps/hidapi")
    message(ERROR ".. or pass a valid -DUHID_HIDAPI_DIR= to cmake")
  else()
    message(STATUS "Using hidapi in ${HIDAPI_DIR}")
  endif()

  set(HIDAPI_INCLUDE_DIRS "${HIDAPI_DIR};${HIDAPI_DIR}/hidapi")
endmacro()

if (WIN32 OR MSYS OR MINGW)
  check_hidapi_package()
  set(HIDAPI_SOURCES "${HIDAPI_DIR}/windows/hid.c")
  set(HIDAPI_LIBRARIES "setupapi")
  set(HIDAPI_STATIC_LIBRARIES ${HIDAPI_LIBRARIES})
elseif(APPLE)
  check_hidapi_package()
  set(HIDAPI_SOURCES "${HIDAPI_DIR}/mac/hid.c")
  set(HIDAPI_LIBRARIES "-framework IOKit -framework CoreFoundation")
  set(HIDAPI_STATIC_LIBRARIES ${HIDAPI_LIBRARIES})
else()
  FIND_PACKAGE(PkgConfig)
  PKG_CHECK_MODULES(HIDAPI hidapi-libusb REQUIRED)
  #hidapi-libusb pkg-config file misses the libusb dependency
  PKG_CHECK_MODULES(LIBUSB libusb-1.0 REQUIRED)
  add_cflag_if_supported( "-fPIC ")
  #Static releases are messy
  if (CMAKE_BUILD_TYPE MATCHES "StaticRelease")
    set(HIDAPI_STATIC_LIBRARIES "-Wl,-Bstatic ${HIDAPI_LDFLAGS} ${LIBUSB_LDFLAGS} -Wl,-Bdynamic -lpthread -ludev")
  endif()
endif()
